import joblib
import numpy as np

# ==========================================
# 1. CRYPTOGRAPHY CONSTANTS
# ==========================================
# Our Quantization Multiplier (2^16)
SCALE_FACTOR = 65536  

# The BabyJubJub Prime (The absolute limit of our finite field)
# All math in our ZK circuit happens modulo this massive 77-digit prime number.
PRIME = 21888242871839275222246405745257275088548364400416034343698204186575808495617

# ==========================================
# 2. FINITE FIELD TRANSLATOR
# ==========================================
def to_finite_field(float_val):
    """
    1. Multiplies the decimal by 65536 and rounds to a whole integer.
    2. Wraps any negative numbers into the positive finite field using Modulo P.
    """
    quantized = int(round(float_val * SCALE_FACTOR))
    
    # In finite fields, a negative number like -5 becomes (P - 5).
    # Python's modulo operator automatically handles this wrap-around beautifully.
    return quantized % PRIME

# ==========================================
# 3. LOAD THE TRAINED MODEL
# ==========================================
print("🧠 Loading zkcredit_model.pkl...")
try:
    model = joblib.load('zkcredit_model.pkl')
except FileNotFoundError:
    print("❌ Error: zkcredit_model.pkl not found. Run the trainer script first!")
    exit()

# Extract floating point Weights (W) and Bias (B)
# Note: model.coef_ is a 2D array, so we grab the first row [0]
raw_weights = model.coef_[0]
raw_bias = model.intercept_[0]

print(f"\n📊 Raw Decimals (Data Science Layer):")
print(f"Weights: {raw_weights}")
print(f"Bias:    {raw_bias}")

# ==========================================
# 4. APPLY QUANTIZATION & MODULO
# ==========================================
zk_weights = [to_finite_field(w) for w in raw_weights]
zk_bias = to_finite_field(raw_bias)

print(f"\n🔐 Finite Field Integers (Cryptography Layer):")
print(f"ZK Weights: {zk_weights}")
print(f"ZK Bias:    {zk_bias}")

# ==========================================
# 5. GENERATE THE .CIRCOM CIRCUIT FILE
# ==========================================
print("\n⚙️  Compiling circuit.circom...")

circom_code = f"""pragma circom 2.0.0;

// ==========================================
// ZK-CREDIT: ON-CHAIN SCORING CIRCUIT
// Auto-generated by Python ZK-Compiler
// ==========================================

template ZKCreditScore() {{
    // 1. Private Inputs (The user's off-chain wallet features)
    // X[0] = Wallet Nonce
    // X[1] = ETH Balance
    // X[2] = Derived Holding Power
    // X[3] = Placeholder
    signal input X[4];
    
    // 2. Public Output (The final Z Score submitted to the Smart Contract)
    signal output Z;

    // 3. Hardcoded ML Parameters (Converted to Finite Field)
    var W0 = {zk_weights[0]};
    var W1 = {zk_weights[1]};
    var W2 = {zk_weights[2]};
    var W3 = {zk_weights[3]};
    var B  = {zk_bias};

    // 4. The Mathematical Forward Pass (Dot Product)
    // We use <== to assign the value AND generate the cryptographic constraint
    Z <== (W0 * X[0]) + (W1 * X[1]) + (W2 * X[2]) + (W3 * X[3]) + B;
}}

// Instantiate the component
// Setting {{public [X]}} is optional, but for our privacy use case, 
// X remains private by default, and ONLY Z is public.
component main = ZKCreditScore();
"""

# Write the string to a physical file
with open("circuit.circom", "w") as f:
    f.write(circom_code)

print("✅ Success! 'circuit.circom' has been generated and is ready for the Prover.")